version: '3'
services:
  content-server:
    build:
      context: .
      dockerfile: ./content-server.Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./broccoli-content-server/content_server.env
    environment:
      - RPC_AMQP_HOSTNAME=rabbitmq
      - RPC_AMQP_PORT=5672
    depends_on:
      - rabbitmq
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 5
  api:
    build:
      context: .
      dockerfile: ./api.Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - ./broccoli-api/api.env
    environment:
      - CONTENT_SERVER_HOSTNAME=content-server
      - CONTENT_SERVER_PORT=5000
    depends_on:
      - content-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001"]
      interval: 30s
      timeout: 10s
      retries: 5
  worker-manager:
    build:
      context: .
      dockerfile: ./worker-manager.Dockerfile
    ports:
      - "5002:5002"
    env_file:
      - ./broccoli-worker-manager/worker_manager.env
      - ./broccoli-worker-manager/workers.env
    environment:
      - RPC_AMQP_HOSTNAME=rabbitmq
      - RPC_AMQP_PORT=5672
    depends_on:
      - rabbitmq
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002"]
      interval: 30s
      timeout: 10s
      retries: 5
  web:
    build:
      context: ./broccoli-web
    ports:
      - "3000:5000"
    env_file:
      - ./broccoli-web/.env.development
      - ./broccoli-web/.env.development.local
    depends_on:
      - content-server
      - api
      - worker-manager
  rabbitmq:
    image: "rabbitmq:3.7.12-management"
    env_file:
      - ./rabbitmq.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
